CI: tests

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -9,18 +9,6 @@ on:
       - develop
 
 jobs:
-  #Install:
-  #  runs-on: ubuntu-latest
-
-  #  steps:
-  #  - name: Checkout
-  #    uses: actions/checkout@v3
-
-  #  - name: Install
-  #    run: |
-  #      chmod 777 ./install.sh;
-  #      ./install.sh;
-
   CPPChecker:
     runs-on: ubuntu-latest
 
@@ -33,30 +21,43 @@ jobs:
 
     - name: Run cppcheck
       run: |
-        ls
         make cppcheck
 
-  #Linter:
-  #  runs-on: ubuntu-latest
-  #  needs: CPPChecker
+  Linter:
+    runs-on: ubuntu-latest
+    needs: CPPChecker
 
-  #  steps:
-  #    - name: Checkout
-  #      uses: actions/checkout@v3
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
 
-  #    - name: Linter
-  #      uses: cpp-linter/cpp-linter-action@v2
-  #      id: linter
-  #      env:
-  #        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #      with:
-  #        style: file
+      - name: Linter
+        uses: cpp-linter/cpp-linter-action@v2
+        id: linter
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          style: file
 
-  #    - name: Fail
-  #      if: steps.linter.outputs.checks-failed > 0
-  #      run: |
-  #        echo "Some files failed the linting checks!";
-  #        exit 1;
+      - name: Fail
+        if: steps.linter.outputs.checks-failed > 0
+        run: |
+          echo "Some files failed the linting checks!";
+          exit 1;
+
+  GoogleTest:
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Checkout
+      uses: actions/checkout@v3
+
+    - name: Install cppcheck
+      run: sudo apt-get install cppcheck
+
+    - name: Run cppcheck
+      run: |
+        make googletest
 
   #Build:
   #  runs-on: ubuntu-latest
