CI: tests

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -32,8 +32,15 @@ jobs:
 
     - name: Install GoogleTest
       run: |
-        git clone https://github.com/google/googletest.git;
-        cd googletest && mkdir -p build && cd build && cmake .. && make && make install;
+        git clone https://github.com/google/googletest.git
+        cd googletest
+        mkdir -p build
+        cd build
+        cmake ..
+        make
+        make install
+        cd ..
+        cd ..
 
     - name: Run GoogleTest
       run: |
@@ -57,8 +64,8 @@ jobs:
       - name: Fail
         if: steps.linter.outputs.checks-failed > 0
         run: |
-          echo "Some files failed the linting checks!";
-          exit 1;
+          echo "Some files failed the linting checks!"
+          exit 1
 
   Build:
     runs-on: ubuntu-latest
@@ -73,7 +80,7 @@ jobs:
 
     - name: Build
       run: |
-        Echo build;
+        Echo build
 
   #CreatePR:
   #  runs-on: ubuntu-latest
